apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    model.aibrix.ai/name: llama-3-8b-instruct
    prometheus-discovery: "true"
  name: llama-3-8b-instruct
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: serve
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    model.aibrix.ai/name: llama-3-8b-instruct
  sessionAffinity: None
  type: ClusterIP
