apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"prometheus.io/port":"8080","prometheus.io/scrape":"true"},"labels":{"model.aibrix.ai/name":"llama-3-8b-instruct","prometheus-discovery":"true"},"name":"llama-3-8b-instruct","namespace":"default"},"spec":{"ports":[{"name":"serve","port":8000,"protocol":"TCP","targetPort":8000},{"name":"http","port":8080,"protocol":"TCP","targetPort":8080}],"selector":{"model.aibrix.ai/name":"llama-3-8b-instruct"},"type":"ClusterIP"}}
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
  creationTimestamp: "2025-04-10T05:46:08Z"
  labels:
    model.aibrix.ai/name: llama-3-8b-instruct
    prometheus-discovery: "true"
  name: llama-3-8b-instruct
  namespace: default
  resourceVersion: "172097501"
  uid: 3c1e3445-7f79-4e09-9bf1-a1026a0e8455
spec:
  clusterIP: 192.168.74.140
  clusterIPs:
  - 192.168.74.140
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: serve
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    model.aibrix.ai/name: llama-3-8b-instruct
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
