apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-service
  namespace: default
  labels:
    app: client-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-service
  template:
    metadata:
      labels:
        app: client-service
    spec:
      # # Bind pod to specific node
      # nodeSelector:
      #   kubernetes.io/hostname: "10.0.1.10"
      containers:
      - name: client
        image: aibrix-container-registry-cn-beijing.cr.volces.com/aibrix/gangmuk-client:latest-vke-gangmuk
        imagePullPolicy: Always
        command: ["sleep", "infinity"]
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "4000m"
        volumeMounts:
        - name: output
          mountPath: /app/output
      volumes:
      - name: output
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: default
spec:
  selector:
    app: client-service
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP

