apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "590"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"routing-agent-service","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"routing-agent-service"}},"strategy":{"rollingUpdate":{"maxSurge":"100%","maxUnavailable":"100%"},"type":"RollingUpdate"},"template":{"metadata":{"labels":{"app":"routing-agent-service"}},"spec":{"affinity":{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"machine.cluster.vke.volcengine.com/gpu-name","operator":"In","values":["NVIDIA-A10"]}]}]}}},"containers":[{"env":[{"name":"PORT","value":"8080"},{"name":"LOG_LEVEL","value":"INFO"}],"image":"aibrix-container-registry-cn-beijing.cr.volces.com/aibrix/gangmuk-routing-agent:latest","imagePullPolicy":"Always","name":"routing-agent","ports":[{"containerPort":8080}],"resources":{"limits":{"cpu":"5000m","memory":"2Gi","nvidia.com/gpu":1},"requests":{"cpu":"200m","memory":"200Mi","nvidia.com/gpu":1}}}],"terminationGracePeriodSeconds":5}}}}
  creationTimestamp: "2025-05-18T01:31:15Z"
  generation: 591
  name: routing-agent-service
  namespace: default
  resourceVersion: "236658005"
  uid: 0d1dcfee-34b3-4deb-bcca-1f05d7611a17
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: routing-agent-service
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-06-16T13:20:04-07:00"
      creationTimestamp: null
      labels:
        app: routing-agent-service
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: machine.cluster.vke.volcengine.com/gpu-name
                operator: In
                values:
                - NVIDIA-L20
      containers:
      - env:
        - name: PORT
          value: "8080"
        - name: LOG_LEVEL
          value: INFO
        - name: EXPLORE_ENABLED
          value: "1"
        - name: EXPLORATION_RATE
          value: "0.1"
        - name: MODEL
          value: simpler_contextual_bandit
        - name: ENABLE_ONLINE_LEARNING
          value: "true"
        - name: TTFT_SLO
          value: "1000"
        - name: AVG_TPOT_SLO
          value: "50"
        image: aibrix-container-registry-cn-beijing.cr.volces.com/aibrix/gangmuk-routing-agent:latest
        imagePullPolicy: Always
        name: routing-agent
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: "5"
            memory: 2Gi
            nvidia.com/gpu: "1"
          requests:
            cpu: 200m
            memory: 200Mi
            nvidia.com/gpu: "1"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 5
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-05-18T01:31:17Z"
    lastUpdateTime: "2025-05-18T01:31:17Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-06-14T19:43:58Z"
    lastUpdateTime: "2025-06-16T20:20:14Z"
    message: ReplicaSet "routing-agent-service-7dd9d67bb8" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 591
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
