apiVersion: apps/v1
kind: Deployment
metadata:
  name: routing-agent-service
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: routing-agent-service
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: routing-agent-service
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: machine.cluster.vke.volcengine.com/gpu-name
                operator: In
                values:
                - NVIDIA-L20
      serviceAccountName: routing-agent-sa
      containers:
      - env:
        - name: PORT
          value: "8080"
        - name: LOG_LEVEL
          value: INFO
        - name: EXPLORE_ENABLED
          value: "1"
        - name: EXPLORATION_RATE
          value: "0.1"
        - name: MODEL
          value: simpler_contextual_bandit
        - name: ENABLE_ONLINE_LEARNING
          value: "true"
        image: gangmuk/gangmuk-routing-agent:latest-linux
        imagePullPolicy: Always
        name: routing-agent
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: "5"
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 200Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 5

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: routing-agent-reader
rules:
- apiGroups: [""] # The core API group
  resources: ["pods", "nodes"]
  verbs: ["get", "list"]

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: routing-agent-sa
  namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: routing-agent-reader-binding
subjects:
- kind: ServiceAccount
  name: routing-agent-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: routing-agent-reader
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: v1
kind: Service
metadata:
  name: routing-agent-service
  namespace: default
spec:
  # clusterIP: 192.168.70.209
  # clusterIPs:
  # - 192.168.70.209
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: routing-agent-service
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
