apiVersion: v1
kind: Service
metadata:
  name: routing-agent-service
  namespace: default
spec:
  # clusterIP: 192.168.70.209
  # clusterIPs:
  # - 192.168.70.209
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: routing-agent-service
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
